In [24]:
import numpy as n
m=n.array([[1,2,3,4],[1,2,3,4],[2,3,4,5],[2,5,6,7]])
r=n.zeros((3,4))
print(f'The elements in the array:{r}')

The elements in the array/n[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [25]:
x=n.full((3,3),2)
print(x)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [74]:
q=n.random.random((3,2))
print(q)

[[0.99370044 0.62185527]
 [0.14024674 0.64875373]
 [0.39044143 0.55256431]]


In [36]:
q1=n.arange(5,50,5)
print(q1)


[ 5 10 15 20 25 30 35 40 45]


In [43]:
w=q.reshape(4,3)
print(w)

[[0.78141956 0.12968031 0.66631671]
 [0.28345055 0.770646   0.09219495]
 [0.36286302 0.74850029 0.35166574]
 [0.7585088  0.72824548 0.00196387]]


In [45]:
print(w.flatten())
print(w.ndim)

[0.78141956 0.12968031 0.66631671 0.28345055 0.770646   0.09219495
 0.36286302 0.74850029 0.35166574 0.7585088  0.72824548 0.00196387]
2


In [47]:
print(w.shape)


(4, 3)


In [49]:
print(w.size)
print(w.dtype)


12
float64


In [53]:
g=w.astype('i')
print(g)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [77]:
print(m[0:3:2])

[[1 2 3 4]
 [2 3 4 5]]


In [75]:
print(m[2,1:4])



[3 4 5]


In [78]:
print(m[:,3])


[4 4 5]


In [ ]:
///NUMPY2///


In [2]:
import numpy as np
arr=np.array([[0,-1,2.5,3],[4,5,6,7],[11.7,6.9,65,8],[9,10,11,108]])
print(arr[0:2:4])


[[ 0.  -1.   2.5  3. ]]


In [3]:
temp=arr[:1,:2]
print(temp)

[[ 0. -1.]]


In [5]:
temp1=arr[[0,1,2,3],[3,2,1,0]]
print(temp1)

[3.  6.  6.9 9. ]


In [6]:
condition=arr>2
temp2=arr[condition]
print(temp2)

[  2.5   3.    4.    5.    6.    7.   11.7   6.9  65.    8.    9.   10.
  11.  108. ]


In [8]:
arr1=np.array([1,2,3,4,5,6,7])
print(arr1[::4])

[1 5]


In [11]:
arr2=np.array([1,2,3,4])
arr3=np.array([5,6,7,8])
ar=np.concatenate((arr2,arr3))
print(ar)

[1 2 3 4 5 6 7 8]


In [12]:
hori=np.hstack((arr2,arr3))
print(hori)
vert=np.vstack((arr2,arr3))
print(vert)
stac=np.dstack((arr2,arr3))
print(stac)


[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [14]:
d=np.array_split(arr1,3)
print(d)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [ ]:
/////////////////////////////////////////////////////////////////

In [ ]:
NUMPY3


In [16]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
print(arr)
x=np.where(arr==4)
print(x)


[1 2 3 4 5 6 4]
(array([3, 6], dtype=int64),)


In [18]:
arr1=np.array([1,2,3,4,5,6,7,8])
e=np.where(arr1%2==0)
print(e)

(array([1, 3, 5, 7], dtype=int64),)


In [21]:
q=np.searchsorted(arr,3,'left')
print(q)

2


In [22]:
a=np.array([3,2,1,0])
print(np.sort(a))


[0 1 2 3]


In [23]:
b=np.array([41,42,43,44])
c=[True,False,True,False]
newarr=b[c]
print(newarr)

[41 43]


In [25]:
we=np.array([41,42,43,45,59,63])
filter=we>42
wer=we[filter]
print(filter)

[False False  True  True  True  True]


In [ ]:
/////////////////////////////////////////////////////////////////////////////////////////

In [ ]:
NUMPY 4

In [26]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[2,4,5,8,10]
a=np.array(arr1)
b=np.array(arr2)
print(a,b)

[10 20 30 40 50] [ 2  4  5  8 10]


In [27]:
print(a+b)#Addition

[12 24 35 48 60]


In [28]:
print(a-b)#Subtraction

[ 8 16 25 32 40]


In [29]:
print(a*b)#Multiplication

[ 20  80 150 320 500]


In [30]:
print(a/b)#Division

[5. 5. 6. 5. 5.]


In [31]:
scl=5#Scalar Multiplication
print(a*scl)


[ 50 100 150 200 250]


In [34]:
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
a1=[10,4,20]
a2=[2,3,30]
vec=np.vectorize(my_func)
print(vec(a1,a2))

[ 8  1 50]


In [ ]:
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
